language:
  - cpp

os:
  - linux
  - osx

dist:
  - xenial

sudo:
  - required

osx_image:
  - xcode9

addons:
  apt:
    packages:
     - libbz2-dev libfftw3-dev libfishsound1-dev libid3tag0-dev liblo-dev liblrdf0-dev libmad0-dev liboggz2-dev libpulse-dev libsamplerate-dev libsndfile-dev libsord-dev libxml2-utils portaudio19-dev qt5-default libqt5svg5-dev raptor-utils yajl-tools mlton

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then brew update ; brew install polyml qt5 raptor yajl; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then export PATH=$PATH:/usr/local/opt/qt5/bin ; fi
  - ( cd ../ ; hg clone https://code.soundsoftware.ac.uk/hg/vamp-plugin-sdk )
  - ( cd ../ ; hg clone https://code.soundsoftware.ac.uk/hg/vamp-test-plugin )
  - ( if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then mkdir -p ~/Library/Audio/Plug-Ins/Vamp ; else mkdir ~/vamp ; fi )
  - ( cd ../vamp-plugin-sdk ; if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then make -f build/Makefile.osx plugins && cp examples/vamp-example-plugins.dylib ~/Library/Audio/Plug-Ins/Vamp/ ; else ./configure --disable-programs && make plugins && cp examples/vamp-example-plugins.so ~/vamp/ ; fi )
  - ( cd ../vamp-test-plugin ; if [[ "$TRAVIS_OS_NAME" = "osx" ]] ; then make -f Makefile.osx && cp vamp-test-plugin.dylib ~/Library/Audio/Plug-Ins/Vamp/ ; else make -f Makefile.linux && cp vamp-test-plugin.so ~/vamp/ ; fi )

before_script:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; then ./configure ; else ./repoint install && qmake -r sonic-annotator.pro ; fi

script:
  - make -j3

